server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mariadb://localhost:3306/traveloo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.5.61
    port: 6379
    password: 
    database: 0

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.traveloo: DEBUG 